### ISSUE TITLE
Factions Mob not respawning 

### ISSUE THREAD

**Issue by downboy** [Scyntrus/FactionMobs#11]
Hallo,

when the server restarts the factions mobs are not respawning in the chunks. is there a config option i have not add or something els?

if you need more info plz tell me.

**Comment by downboy** [comment]
`[2017/07/08 21:56:12] java.lang.NullPointerException
	at com.gmail.scyntrus.ifactions.k.KingdomsConnector.getFactionByName(KingdomsConnector.java:44)
	at com.gmail.scyntrus.ifactions.FactionsManager.getFactionByName(FactionsManager.java:86)
	at com.gmail.scyntrus.fmob.FactionMobs.loadMobList(FactionMobs.java:287)
	at com.gmail.scyntrus.fmob.FactionMobs.onEnable(FactionMobs.java:244)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by Scyntrus** [comment]
Well, took almost a year for me to get around to looking at this, but I couldn't find a way to reproduce this. Only reason this would happen is if Kingdoms doesn't load.
