### ISSUE TITLE
Not compatible with Towny.

### ISSUE THREAD

**Issue by SROrel** [Scyntrus/FactionMobs#26]
Althrough it says it's fully compatible with Towny, it's not. It works only with factions plugins for some reason.

**Comment by darealHeroBrine** [comment]
You would probably have to enable it in either town or fm

**Comment by darealHeroBrine** [comment]
If you are using Towny, you must set the 'force_town_monsters_on' to true in Towny's config.yml.

**Comment by GIToez** [comment]
> If you are using Towny, you must set the 'force_town_monsters_on' to true in Towny's config.yml.

What version of towny/faction mobs are you using?

**Comment by GIToez** [comment]
`ERROR Could not load 'plugins/FactionMobs.jar' in folder 'plugins'
29.10 23:58:55 [Server] INFO org.bukkit.plugin.UnknownDependencyException: Factions
29.10 23:58:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:223) [SimplePluginManager.class:1.7.10-1448.133]
29.10 23:58:55 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:1.7.10-1448.133]
29.10 23:58:55 [Server] INFO at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]
29.10 23:58:55 [Server] INFO at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
29.10 23:58:55 [Server] INFO at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
29.10 23:58:55 [Server] INFO at net.minecraft.world.WorldServer.<init>(WorldServer.java:158) [mt.class:?]
29.10 23:58:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
29.10 23:58:55 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
29.10 23:58:55 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]`
